### ISSUE TITLE
Update the website

### ISSUE THREAD

**Issue by dleslie** [CSSS/minutes#5]
These minutes are not posted on the website.

**Comment by jleung51** [comment]
Actually, they are!

http://sfucsss.org/about/documents/

**Comment by dleslie** [comment]
Ah, so it appears as though the front page of the website poorly reflects the level of activity of the society.

**Comment by modernNeo** [comment]
Hi @dleslie.

as you may have noticed, the front page of our website is not up to date. As I mentioned before, I am actively working on setting up a new website but of course, like with any open-source project, life can get in the way :)
I appreciate you wanting to point out the various ways this effects us but rest assured, I am fully aware and will resolve when I can, but given that the code I am working on is in a private repo, its progress is not public. When it is done and made public, you are welcome to detect any issues in the v3 of our website :)

Until then, I will close this Issue as its not relevant to the minute repo but more to the new website repo which is not open to the public just yet.
